#________________________________________
# Stages
#----------------------------------------
stages:
  - build
  - test

#________________________________________
# Jobs
#----------------------------------------
.build-job:
  stage: build
  before_script:
    - python -m pip install --upgrade pip
    - pip install -U nox
    - uname -a

Python3.7:
  extends: .build-job
  image: python:3.7.16
  script:
    - nox -r -f ./noxfile.py -s build

Python3.8:
  extends: .build-job
  image: python:3.8.16
  script:
    - nox -r -f ./noxfile.py -s build

Python3.9:
  extends: .build-job
  image: python:3.9.16
  script:
    - nox -r -f ./noxfile.py -s build

Python3.10:
  extends: .build-job
  image: python:3.10.9
  script:
    - nox -r -f ./noxfile.py -s build
